In [ ]:
# Mendapatkan nilai eigen untuk molekul hidrogen: energi ikatan dan antiikatan
import numpy as np
from scipy.linalg import eigh

eps0 = 0.
t    = -3.
s    = 0.1

H = np.array([[eps0, t   ],
              [t   , eps0]])

S = np.array([[1, s],
              [s, 1]])

E,C = eigh(H, S)
print('E-value:', E)
print('E-vector', C)

E-value: [-2.72727273  3.33333333]
E-vector [[-0.67419986 -0.74535599]
 [-0.67419986  0.74535599]]


In [ ]:
# mengecek dengan hasil analitik

Erendah = (eps0-t) / (1-s)
Etinggi = (eps0+t) / (1+s)

print('energi ikatan:', Erendah)
print('energi antiikatan:', Etinggi)

energi ikatan: 3.333333333333333
energi antiikatan: -2.727272727272727


In [ ]:
# Mendapatkan nilai eigen untuk molekul litium (Li3) rantai linear
import numpy as np
from scipy.linalg import eigh

eps0 = 0
t    = -1
s    = 0

H = np.array([[eps0, t    , eps0 ],
              [t   , eps0 , t    ],
              [eps0, t    , eps0 ]])

S = np.array([[1, s, 0],
              [s, 1, s],
              [0, s, 1]])

E,C = eigh(H, S)
print('E-value:', E)
print('E-vector', C)

E-value: [-1.41421356e+00 -6.07153217e-18  1.41421356e+00]
E-vector [[-5.00000000e-01 -7.07106781e-01  5.00000000e-01]
 [-7.07106781e-01 -4.85722573e-17 -7.07106781e-01]
 [-5.00000000e-01  7.07106781e-01  5.00000000e-01]]


In [ ]:
# Mendapatkan nilai eigen untuk molekul litium (Li3) segitiga
import numpy as np
from scipy.linalg import eigh

eps0 = 0
t    = -1
s    = 0

H = np.array([[eps0, t    , t    ],
              [t   , eps0 , t    ],
              [t   , t    , eps0 ]])

S = np.array([[1, s, 0],
              [s, 1, s],
              [0, s, 1]])

E,C = eigh(H, S)
print('E-value:', E)
print('E-vector', C)

E-value: [-2.  1.  1.]
E-vector [[ 0.57735027 -0.42250331  0.69868277]
 [ 0.57735027  0.81632869  0.01655721]
 [ 0.57735027 -0.39382538 -0.71523999]]
